/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scrape Prometheus metrics
         * @description Keep this endpoint on a private monitoring network; do not expose it through the public ingress.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text exposition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user, organization, and session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Register"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Login"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Refresh"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh-token family */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Refresh"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all refresh sessions for the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create an organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Organization"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** Read an organization */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename an organization */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Organization"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List organization members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/members/{membershipID}/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                membershipID: components["parameters"]["MembershipID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a role to a member */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    membershipID: components["parameters"]["MembershipID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["AssignRole"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List roles and permissions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a custom role */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Role"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/roles/{roleID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                roleID: components["parameters"]["RoleID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an unused custom role */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    roleID: components["parameters"]["RoleID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Update a custom role */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    roleID: components["parameters"]["RoleID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Role"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/audit-logs": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /**
         * List tenant audit events
         * @description Requires the audit.read permission; time filters are limited to the preceding 90 days.
         */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    action?: string;
                    outcome?: "success" | "failure" | "denied";
                    actor_user_id?: string;
                    since?: string;
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Team"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/teams/{teamID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                teamID: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        /** Read a team */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a team */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Update a team */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Team"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/teams/{teamID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                teamID: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        /** List team members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Add an active organization member to a team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["TeamMember"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/teams/{teamID}/members/{teamMemberID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                teamID: components["parameters"]["TeamID"];
                teamMemberID: components["parameters"]["TeamMemberID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a team member */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    teamID: components["parameters"]["TeamID"];
                    teamMemberID: components["parameters"]["TeamMemberID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List projects */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    status?: "planning" | "active" | "on_hold" | "completed" | "archived";
                    priority?: "low" | "medium" | "high" | "urgent";
                    team_id?: string;
                    sort?: "created_at" | "updated_at" | "name" | "due_date" | "priority";
                    order?: components["parameters"]["Order"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["CreateProject"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** Read a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a project and its tasks */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Update a project */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateProject"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/projects/{projectID}/activity": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** List project activity */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List organization tasks */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    project_id?: string;
                    status?: "todo" | "in_progress" | "blocked" | "in_review" | "done" | "cancelled";
                    priority?: "low" | "medium" | "high" | "urgent";
                    assignee_id?: string;
                    unassigned?: boolean;
                    sort?: "created_at" | "updated_at" | "title" | "due_date" | "priority" | "status";
                    order?: components["parameters"]["Order"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/tasks/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** Read a task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Update a task */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["UpdateTask"];
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/tasks/{taskID}/activity": {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** List task activity */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/projects/{projectID}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** List tasks in a project */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    status?: "todo" | "in_progress" | "blocked" | "in_review" | "done" | "cancelled";
                    priority?: "low" | "medium" | "high" | "urgent";
                    assignee_id?: string;
                    unassigned?: boolean;
                    sort?: "created_at" | "updated_at" | "title" | "due_date" | "priority" | "status";
                    order?: components["parameters"]["Order"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a task in a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["CreateTask"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List invitations */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    status?: "pending" | "accepted" | "revoked" | "expired";
                    email?: string;
                    sort?: "created_at" | "expires_at" | "email";
                    order?: components["parameters"]["Order"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /**
         * Invite an email address to the organization
         * @description The invitation token is delivered by email and is never returned in this response.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Invite"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/invitations/{invitationID}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                invitationID: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend a pending invitation and rotate its token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    invitationID: components["parameters"]["InvitationID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/invitations/{invitationID}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                invitationID: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a pending invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    invitationID: components["parameters"]["InvitationID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description One-time invitation bearer token. */
                token: string;
            };
            cookie?: never;
        };
        /** Preview an invitation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description One-time invitation bearer token. */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation and issue a session
         * @description Existing users may send only token with a bearer session; new users also send password, first_name, and last_name.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["AcceptInvitation"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** List API keys */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    include_revoked?: boolean;
                    sort?: "created_at" | "expires_at" | "last_used_at";
                    order?: components["parameters"]["Order"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Page"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /**
         * Create an API key
         * @description The secret is returned once in this response; store it securely.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["CreateAPIKey"];
            responses: {
                201: components["responses"]["Created"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgID}/api-keys/{apiKeyID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                apiKeyID: components["parameters"]["APIKeyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    apiKeyID: components["parameters"]["APIKeyID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @description Endpoint-specific DTO, array, or small status object. */
            data: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            }[] | string | boolean;
        };
        PageEnvelope: {
            data: {
                [key: string]: unknown;
            }[];
            pagination: components["schemas"]["Pagination"];
        };
        Pagination: {
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: string;
                };
                request_id?: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            first_name: string;
            last_name: string;
            organization_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        OrganizationRequest: {
            name: string;
        };
        AssignRoleRequest: {
            /** Format: uuid */
            role_id: string;
        };
        RoleRequest: {
            name: string;
            description?: string;
            permissions?: string[];
        };
        TeamRequest: {
            name: string;
            description?: string;
        };
        TeamMemberRequest: {
            /** Format: uuid */
            user_id: string;
        };
        CreateProjectRequest: {
            name: string;
            description?: string | null;
            /** Format: uuid */
            team_id?: string | null;
            /** @enum {string} */
            status?: "planning" | "active" | "on_hold" | "completed" | "archived";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            due_date?: string | null;
        };
        UpdateProjectRequest: {
            name?: string;
            description?: string | null;
            /** Format: uuid */
            team_id?: string | null;
            /** @enum {string} */
            status?: "planning" | "active" | "on_hold" | "completed" | "archived";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            due_date?: string | null;
        };
        CreateTaskRequest: {
            title: string;
            description?: string | null;
            /** @enum {string} */
            status?: "todo" | "in_progress" | "blocked" | "in_review" | "done" | "cancelled";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: date */
            due_date?: string | null;
        };
        UpdateTaskRequest: {
            title?: string;
            description?: string | null;
            /** @enum {string} */
            status?: "todo" | "in_progress" | "blocked" | "in_review" | "done" | "cancelled";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: date */
            due_date?: string | null;
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            /** Format: uuid */
            role_id: string;
        };
        AcceptInvitationRequest: {
            token: string;
            /** Format: password */
            password?: string;
            first_name?: string;
            last_name?: string;
        };
        CreateAPIKeyRequest: {
            name: string;
            expires_in_days?: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            /** Format: uri */
            avatar_url?: string | null;
            status: string;
            /** Format: date-time */
            email_verified_at?: string | null;
            /** Format: date-time */
            last_login_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: string;
            role?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            team_id?: string | null;
            name: string;
            description?: string | null;
            status: string;
            priority: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            due_date?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            description?: string | null;
            status: string;
            priority: string;
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: date */
            due_date?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuthSession: {
            access_token: string;
            refresh_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in: number;
            user: components["schemas"]["User"];
        };
        Member: {
            /** Format: uuid */
            membership_id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            role: string;
            status: string;
            /** Format: date-time */
            joined_at?: string | null;
        };
        Role: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            description?: string | null;
            is_system: boolean;
            permissions: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Team: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            name: string;
            description?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TeamMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            /** Format: date-time */
            created_at: string;
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: email */
            email: string;
            /** Format: uuid */
            role_id: string;
            role_name?: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "revoked" | "expired";
            /** Format: uuid */
            invited_by: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: uuid */
            accepted_by?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InvitationPreview: {
            /** Format: uuid */
            organization_id: string;
            organization_name: string;
            /** Format: email */
            email: string;
            role_name: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "revoked" | "expired";
            /** Format: date-time */
            expires_at: string;
            account_exists: boolean;
            /** Format: uuid */
            accepted_by?: string | null;
        };
        APIKey: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            created_by: string;
            name: string;
            key_prefix: string;
            key_last_four: string;
            /** @enum {string} */
            status: "active" | "expired" | "revoked";
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreatedAPIKey: {
            api_key: components["schemas"]["APIKey"];
            /** @description Secret shown only once. Do not log or persist in client-visible history. */
            key: string;
            warning: string;
        };
    };
    responses: {
        /** @description Request completed successfully. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SuccessEnvelope"];
            };
        };
        /** @description Resource created successfully. */
        Created: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SuccessEnvelope"];
            };
        };
        /** @description Paginated collection response. */
        Page: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PageEnvelope"];
            };
        };
        /** @description Error response; internal details are not exposed. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        OrgID: string;
        MembershipID: string;
        RoleID: string;
        TeamID: string;
        TeamMemberID: string;
        ProjectID: string;
        TaskID: string;
        InvitationID: string;
        APIKeyID: string;
        Page: number;
        PageSize: number;
        Order: "asc" | "desc";
    };
    requestBodies: {
        Register: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        Login: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        Refresh: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        Organization: {
            content: {
                "application/json": components["schemas"]["OrganizationRequest"];
            };
        };
        AssignRole: {
            content: {
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        Role: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        Team: {
            content: {
                "application/json": components["schemas"]["TeamRequest"];
            };
        };
        TeamMember: {
            content: {
                "application/json": components["schemas"]["TeamMemberRequest"];
            };
        };
        CreateProject: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        UpdateProject: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        CreateTask: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        UpdateTask: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        Invite: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        AcceptInvitation: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        CreateAPIKey: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
